toolchains: exclude using remote toolchains in local build
Today, when we perform a build, Bazel would automatically detect
which toolchains are registered and select them automatically based on
the constraint_value attached to the exec platform and toolchain.

In the case of local Linux build, the resolution process goes like this

```
> bazel build @zlib//... --toolchain_resolution_debug='@bazel_tools//tools/cpp:toolchain_type'

Type @bazel_tools//tools/cpp:toolchain_type:
  target platform @local_config_platform//:host:
    execution @local_config_platform//:host:
      Selected toolchain @buildbuddy_toolchain//:ubuntu_local_cc_toolchain

Type @bazel_tools//tools/cpp:toolchain_type:
  target platform @local_config_platform//:host:
    Rejected toolchain @local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android

Type @bazel_tools//tools/cpp:toolchain_type:
  target platform @local_config_platform//:host:
    execution platform @local_config_platform//:host:
      Skipping toolchain @local_config_cc//:cc-compiler-k8; execution platform already has selected toolchain

Target platform @local_config_platform//:host: Selected execution platform @local_config_platform//:host, type @bazel_tools//tools/cpp:toolchain_type -> toolchain @buildbuddy_toolchain//:ubuntu_local_cc_toolchain
```

Note how `@buildbuddy_toolchain//:ubuntu_local_cc_toolchain` wins over
the default `@local_config_cc//:cc-compiler-k8`.

The problem is `@buildbuddy_toolchain//:ubuntu_local_cc_toolchain` comes
with our special `@buildbuddy_toolchain//:ubuntu_cc_toolchain_config`,
which makes some specific assumption about the execution platform. One
of those assumption is the exec platform has GCC 9 pre-installed with
the following include paths.

```
> bazel query @buildbuddy_toolchain//:ubuntu_cc_toolchain_config --output=build

cc_toolchain_config(
  name = "ubuntu_cc_toolchain_config",
  ...
  cpu = "k8",
  cxx_builtin_include_directories = [
    "/usr/include",
    "/usr/include/c++/9",
    "/usr/include/c++/9/backward"
    "/usr/include/x86_64-linux-gnu",
    "/usr/include/x86_64-linux-gnu/c++/9",
    "/usr/lib/gcc/x86_64-linux-gnu/9/include",
    "/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed",
    "/usr/local/include",
  ],
  ...
)
```

However, many users may have a different GCC version installed on their
local system with the standard libraries set in different paths.
When this happens, Bazel CppCompile action will conduct a throrough
import check and generate an error like this with GCC 12.

```
ERROR: /home/.../external/zlib/BUILD.bazel:37:11: Compiling zutil.c failed: undeclared inclusion(s) in rule '@zlib//:zlib':
this rule is missing dependency declarations for the following files included by 'zutil.c':
  '/usr/lib/gcc/x86_64-linux-gnu/12/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/12/include/limits.h'
  '/usr/lib/gcc/x86_64-linux-gnu/12/include/syslimits.h'
  '/usr/lib/gcc/x86_64-linux-gnu/12/include/stdarg.h'
```

or like this with GCC 11.

```
ERROR: /home/.../external/com_google_absl/absl/base/BUILD.bazel:53:11: Compiling absl/base/log_severity.cc [for tool] failed: undeclared inclusion(s) in rule '@com_google_absl//absl/base:log_severity':
this rule is missing dependency declarations for the following files included by 'absl/base/log_severity.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/stdarg.h'
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/stdint.h'
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/limits.h'
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/syslimits.h'
```

A proper fix to this issue is to start using a hermetic CC toolchain
where the stdlib are downloaded and managed by Bazel instead of coming
from the underlying exec platform (local laptop, remote container image
etc...).

As we are pursuing that effort separately in another PR, let's apply a
temporary workaround. By setting a constraint value on our custom
platform definition and our toolchain declaration, we avoid matching our
remote-only toolchain with the local Linux platform. Effectively, it
switch our toolchain resolution process into something like this.

```
Type @bazel_tools//tools/cpp:toolchain_type:
  execution platform @local_config_platform//:host:
    Rejected toolchain @buildbuddy_toolchain//:ubuntu_local_cc_toolchain; mismatching values: gcc

Type @bazel_tools//tools/cpp:toolchain_type:
  target platform @local_config_platform//:host:
    Rejected toolchain @local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android

Type @bazel_tools//tools/cpp:toolchain_type:
  target platform @local_config_platform//:host:
    execution @local_config_platform//:host:
      Selected toolchain @local_config_cc//:cc-compiler-k8

Target platform @local_config_platform//:host: Selected execution platform @local_config_platform//:host, type @bazel_tools//tools/cpp:toolchain_type -> toolchain @local_config_cc//:cc-compiler-k8
```

This means that `@buildbuddy_toolchain//:ubuntu_local_cc_toolchain` will
not be used when building when the exec platform is
`@local_config_platform//:host` where the constraint_value of
`@bazel_tools//tools/cpp:gcc` is not available.