Retry internal errors on task lease stream (#9162)
We saw an instance of `Error updating lease for task: "TASK_ID": rpc
error: code = Internal desc = stream terminated by RST_STREAM with error
code: INTERNAL_ERROR`. Make sure to retry these. Also, elevate these
errors to ERROR level to make them stand out more in the logs, since
these errors are the root cause if a task is canceled.