Use `test.no-sandbox` exec property (#11911)
These targets were failing to build with the `no-sandbox` tag set with
the error:

```
ERROR: no usable strategy found: GoTestGenTest <path/to/test/source.go> failed: GoTestGenTest spawn, which requires sandboxing due to path mapping, cannot be executed with any of the available strategies: [worker, linux-sandbox, standalone]. Your --spawn_strategy, --genrule_strategy, --strategy and/or --allowed_strategies_by_exec_platform flags are probably too strict.
```

Per Fabian's suggestion, switch to using the `test.no-sandbox` exec
property.