Use the Xcode command-line tools instead of Xcode in Mac release workflows
As of Bazel 7.0 we aren’t using the apple_support cc_toolchain. Only `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk` is included in `builtin_include_directories`. If we have `DEVELOPER_DIR` set to something else we can see errors like following:

```
ERROR: /private/var/tmp/_bazel_brentley/7e5d3aaeb704234ad9b80179b286c374/external/com_google_absl/absl/base/BUILD.bazel:95:11: Compiling absl/base/internal/spinlock_wait.cc [for tool] failed: absolute path inclusion(s) found in rule '@@com_google_absl//absl/base:spinlock_wait':
the source file 'absl/base/internal/spinlock_wait.cc' includes the following non-builtin files with absolute paths (if these are builtin files, make sure these paths are in your toolchain):
  '/Applications/Xcode-15.1.0-Release.Candidate.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/atomic'
```

Setting `DEVELOPER_DIR` in our GitHub release workflows ensures that we use the command-line tools rather than whatever is installed on the runner. We also needed to set `--{host,}action_env=DEVELOPER_DIR` to prevent a mismatch between the version of `DEVELOPER_DIR` that Bazel itself sees and what actions/repos see. Finally, I added `BAZEL_NO_APPLE_CPP_TOOLCHAIN=1` to make sure we don’t use the apple_support cc_toolchain.

Signed-off-by: Brentley Jones <github@brentleyjones.com>