oci: update distribution reference (#8931) (#8938)
Replace docker/distribution/reference with a newer version of that
package at distribution/reference.

This helps us avoid potential compilcation error spotted while migrating
to bzlmod:

```
external/gazelle++go_deps+com_github_docker_distribution/reference/reference_deprecated.go:122:19: undefined: reference.SplitHostname
compilepkg: error running subcommand external/rules_go++go_sdk+buildbuddy__download_0/pkg/tool/darwin_arm64/compile: exit status 2
```

Example invocation:

https://buildbuddy.buildbuddy.io/invocation/708b4308-2da8-4cec-8132-c2eb9a038889#@45

`SplitHostname` was deprecated and yanked in the latest version of
distribution/reference.


https://pkg.go.dev/github.com/docker/distribution/reference#SplitHostname

https://github.com/distribution/reference/commit/4894124079e525c3c3c5c8aacaa653b5499004e9