Revert bazel 8 upgrade (#8299)
Reverts buildbuddy-io/buildbuddy#8292

Breaks rules_k8s:
```
	File "/home/vadim/.cache/bazel/_bazel_vadim/6f184f57ee0ec63880c4d01d291bbab7/external/io_bazel_rules_k8s/k8s/object.bzl", line 125, column 10, in _impl
		).to_json(),
Error: 'struct' value has no field or method 'to_json'
```

cc @fmeum