invocation_error_card: reduce noise on user abort event
When a user abort a build, our current error card would show:

```
Build aborted

ERROR: user interrupted
ERROR: //foo:bar: user interrupted
ERROR: //baz/baa:fou: user interrupted
...
```

which can be noisy, especially when
`experimental_cancel_concurrent_tests` was used when multiple test
executions were cancelled in parallel.

Reduce the noise by capturing only the first Aborted event with
USER_INTERRUPTED reason. Also include TargetCompleted label to the
error log. This means that we should only show

```
Build aborted

ERROR: //first/canceled:target: user interrupted
```

from the targetCompleted event in this card.