sandbox_test: fix broken test
`config.RegisterAndParseFlags()` has been removed since #1938 so this
test has been failing to compile for quite some times.

```
enterprise/server/remote_execution/containers/sandbox/sandbox_test.go:41:9: undefined: config.RegisterAndParseFlags
enterprise/server/remote_execution/containers/sandbox/sandbox_test.go:77:9: undefined: config.RegisterAndParseFlags
```

`//server/config` is now auto initialized on startup so let's remote the
rootDirFlag check all together.