Revert "Migrate to rules_js" (#8754)
Reverts buildbuddy-io/buildbuddy#8727

breaks autopush

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/runner/work/buildbuddy-internal/buildbuddy-internal/website/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/runner/work/buildbuddy-internal/buildbuddy-internal/website/node_modules/webpack/lib/util/createHash.js:46:50)
    at /home/runner/work/buildbuddy-internal/buildbuddy-internal/website/node_modules/webpack/lib/FileSystemInfo.js:2[677](https://github.com/buildbuddy-io/buildbuddy-internal/actions/runs/14038081183/job/39301020447#step:11:678):9
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9) ***
```